##
##  Makefile -- Build procedure for sample scheme Apache module
##  Autogenerated via ``apxs -n scheme -g''.
##

builddir=$(shell pwd)
#builddir=/usr/local/src/mod_scheme
top_srcdir=/usr/local/apache2
top_builddir=/usr/local/apache2
include /usr/local/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEF=-Dmy_define=my_value
#INC=-Imy/include/dir
INC=-I/usr/include/sys
#LIB=-Lmy/lib/dir -lmylib
APACHE_INCLUDE=/usr/local/apache2/include
APR_INCLUDE=/usr/local/include/apr-1

#   the default target
all: gen local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clobber:
	-rm -f mod_scheme.o mod_scheme.lo mod_scheme.slo scheme.slo mod_scheme.la \
		scheme.o scheme.lo dynload.o dynload.slo dynload.la callback.o callback.lo callback.slo \
		apache_tie.o apache_symbols.o internal.o
	-rm -f apache/gen/*.*
	-rm -f apache/auxiliary/*.o 
	-rm -f apache_tie.lo apache_symbols.lo internal.lo \
		apache_tie.slo apache_symbols.slo internal.slo 
	-rm -f apache_gen aux_gen
	-rm -f apache/gen/*.tpl.* apache/gen/*.stpl.* apache/gen/*.html
	-rm -f apache/auxiliary/*.stpl.i.c apache/auxiliary/*.stpl.o.c apache/auxiliary/*.tpl.i.c apache/auxiliary/*.tpl.o.c apache/auxiliary/*.html
	-rm -rf .libs
	-rm -f mod_scheme_bin.*

gen: apache_gen aux_gen

apache_gen:
	-rm -rf .deps;touch .deps
	cd apache;perl ../tools/parseh.pl $(APACHE_INCLUDE) $(APR_INCLUDE)
	cd apache;perl ../tools/sparseh.pl $(APACHE_INCLUDE) $(APR_INCLUDE)
	cd apache;perl ../tools/gencallback.pl gen gen -def
	cd apache;perl ../tools/gencallback.pl gen gen -dec
	cd apache;perl ../tools/gencallback.pl gen gen -doc
	cd apache;perl ../tools/genstruct.pl gen gen -def
	cd apache;perl ../tools/genstruct.pl gen gen -dec
	cd apache;perl ../tools/genstruct.pl gen gen -doc
	cd apache;perl ../tools/generate_tie.pl gen $(APACHE_INCLUDE) $(APR_INCLUDE)
	echo > apache_gen

aux_gen:
	cd apache/auxiliary;perl ../../tools/gencallback.pl auxiliary . -def
	cd apache/auxiliary;perl ../../tools/gencallback.pl auxiliary . -dec
	cd apache/auxiliary;perl ../../tools/gencallback.pl auxiliary . -doc
	cd apache/auxiliary;perl ../../tools/genstruct.pl auxiliary . -def
	cd apache/auxiliary;perl ../../tools/genstruct.pl auxiliary . -dec
	cd apache/auxiliary;perl ../../tools/genstruct.pl auxiliary . -doc
	echo > aux_gen

#   simple test
test: reload
	lynx -mime_header http://localhost/scheme

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

bundle:
	-rm -rf release;mkdir release;mkdir release/docs;mkdir release/tinyscheme;mkdir release/htdocs; mkdir release/init; mkdir release/conf; mkdir release/dist
	#cp ./.libs/mod_scheme.so ./release/
	cp ./dist/* ./release/dist
	cp ./apache/gen/*.html ./release/docs/
	cp ./apache/auxiliary/*.html ./release/docs/
	cp hack_mod_scheme.txt ./release/docs/
	cp readme.txt ./release/docs/
	cp install.txt ./release/docs/
	cp mod_scheme-license.txt ./release/docs/
	cp ./tinyscheme/changes ./tinyscheme/copying ./tinyscheme/hack.txt ./tinyscheme/manual.txt \
	./tinyscheme/minischemetribute.txt ./tinyscheme/tinyscheme-license.txt ./tinyscheme/tinyscm.txt ./release/tinyscheme/
	cp ./examples/get.scm ./release/htdocs/
	cp ./examples/post.html ./release/htdocs/
	cp ./examples/*.scm ./release/init/
	cp ./examples/*.conf ./release/conf/
	tar -cf mod_scheme_bin.tar ./release;gzip mod_scheme_bin.tar
	echo "The mod_scheme binary is now available as ./mod_scheme_bin.tar.gz"
