#0,	^_char,		0,	ap,	get_server_version
#0,	void,		0,	ap,	add_version_component,	^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	get_server_built
#0,	void,		0,	ap,	field_noparam,		^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	ht_time,		^_apr_pool_t,0,apr_time_t,1,^_char,0,int,1
#0,	^_char,		0,	ap,	getword,		^_apr_pool_t,0,^^_char,0,char,1
#0,	^_char,		0,	ap,	getword_nc,		^_apr_pool_t,0,^^_char,0,char,1
#0,	^_char,		0,	ap,	getword_white,		^_apr_pool_t,0,^^_char,0
#0,	^_char,		0,	ap,	getword_white_nc,	^_apr_pool_t,0,^^_char,0
#0,	^_char,		0,	ap,	getword_nulls,		^_apr_pool_t,0,^^_char,0,char,1
#0,	^_char,		0,	ap,	getword_nulls_nc,	^_apr_pool_t,0,^^_char,0,char,1
#0,	^_char,		0,	ap,	getword_conf,		^_apr_pool_t,0,^^_char,0
#0,	^_char,		0,	ap,	getword_conf_nc,	^_apr_pool_t,0,^^_char,0
#0,	^_char,		0,	ap,	resolve_env,		^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	size_list_item,		^^_char,0,^_int,0
#0,	^_char,		0,	ap,	get_list_item,		^_apr_pool_t,0,^^_char,0
#0,	int,		1,	ap,	find_list_item,		^_apr_pool_t,0,^_char,0,^_char,0
#0,	^_char,		0,	ap,	get_token,		^_apr_pool_t,0,^^_char,0,int,1
#0,	int,		1,	ap,	find_token,		^_apr_pool_t,0,^_char,0,^_char,0
#0,	int,		1,	ap,	find_last_token,	^_apr_pool_t,0,^_char,0,^_char,0
#0,	int,		1,	ap,	is_url,			^_char,0
#0,	int,		1,	ap,	unescape_url,		^_char,0
#0,	int,		1,	ap,	unescape_url_keep2f,	^_char,0
#0,	void,		0,	ap,	no2slash,		^_char,0
#0,	void,		0,	ap,	getparents,		^_char,0
#0,	^_char,		0,	ap,	escape_path_segment,	^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	os_escape_path,		^_apr_pool_t,0,^_char,0,int,0
0,	^_char,		0,	ap,	escape_uri,		^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	escape_html,		^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	escape_logitem,		^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	construct_server,	^_apr_pool_t,0,^_char,0,apr_port_t,1,^_request_rec,0
#0,	^_char,		0,	ap,	escape_shell_cmd,	^_apr_pool_t,0,^_char,0
#0,	int,		1,	ap,	count_dirs,		^_char,0
#0,	^_char,		0,	ap,	make_dirstr_prefix,	^_char,0,^_char,0,int,1
#0,	^_char,		0,	ap,	make_dirstr_parent,	^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	make_full_path,		^_apr_pool_t,0,^_char,0,^_char,0
#0,	int,		1,	ap,	os_is_path_absolute,	^_apr_pool_t,0,^_char,0
#0,	int,		1,	ap,	is_matchexp,		^_char,0
#0,	int,		1,	ap,	strcmp_match,		^_char,0,^_char,0
#0,	int,		1,	ap,	strcasecmp_match,	^_char,0,^_char,0
#0,	^_char,		0,	ap,	strcasestr,		^_char,0,^_char,0
#0,	^_char,		0,	ap,	stripprefix,		^_char,0,^_char,0
#0,	^_char,		0,	ap,	pbase64decode,		^_apr_pool_t,0,^_char,0
#0,	^_char,		0,	ap,	pbase64encode,		^_apr_pool_t,0,^_char,0
#0,	^_regex_t,	0,	ap,	pregcomp,		^_apr_pool_t,0,^_char,0,int,1
#0,	void,		0,	ap,	pregfree,		^_apr_pool_t,0,^_regex_t,0
0,	int,		1,	ap,	regexec,		^_regex_t,0,^_char,0,size_t,1,^_regmatch_t,0,int,1
#0,	size_t,		1,	ap,	regerror,		int,1,^_regex_t,0,^_char,0,size_t,1
0,	^_char,		0,	ap,	pregsub,		^_apr_pool_t,0,^_char,0,^_char,0,size_t,1,^_regmatch_t,0
#0,	void,		0,	ap,	content_type_tolower,	^_char,0
#0,	void,		0,	ap,	str_tolower,		^_char,0
#0,	int,		1,	ap,	ind,			^_char,0,char,1
#0,	int,		1,	ap,	rind,			^_char,0,char,1
#0,	^_char,		0,	ap,	escape_quotes,		^_apr_pool_t,0,^_char,0
#0,	int,		1,	ap,	is_rdirectory,		^_apr_pool_t,0,^_char,0
#0,	int,		1,	ap,	is_directory,		^_apr_pool_t,0,^_char,0
0,	^_char,		0,	ap,	psignature,		^_char,0,^_request_rec,0
