(display (string-append "<b>Path - Info: </b>" (http:path-info)))
(display "<p/>")
(display (string-append "<b>URI: </b>" (http:uri)))
(display "<p/>")
(display (string-append "<b>Method: </b>" (http:method)))
(display "<p/>")
(display (string-append "<b>Handler: </b>" (http:handler)))
(display "<p/>")
(display (string-append "<b>Request: </b>"  (http:the-request)))
(display "<p/>")
(display (string-append "<b>Get Args: </b>" (http:args)))
(display "<p/>")
(display (string-append "<b>Post Args: </b>"  (http:content)))
(display "<p/>")
(display (string-append "<b>Host: </b>"  (http:hostname)))
(display "<p/>")
(display (string-append "<b>Encoding: </b>"  (http:content-encoding)))
(display "<p/>")
(display (string-append "<b>File: </b>"  (http:filename)))
